### ISSUE TITLE
Aggregated Graph type

### ISSUE THREAD

**Issue by oneilsh** [NCATSTranslator/TranslatorArchitecture#4]
Aggregated graphs are mentioned as a kind of KP, but they are built from other KPs which is generally disallowed. This must be a special case to handle how much data is necessary to build an aggregated graph (such that it wouldn't make sense to build it from ARA queries)? 

Is BigKG in the figure such an aggregate? 

I'll have to dig in a little more to see where the platform services integrate.

**Comment by patrickkwang** [comment]
Yes, "Big KG" and aggregated knowledge graph (AKG) refer to the same type of thing. I think I've also heard "shared knowledge graph".

These AKGs may behave like KPs from the perspective of an ARA, but maybe it will be easier to think about them as a separate fourth type of Translator component.

**Comment by oneilsh** [comment]
Sounds good, AKGs as a 4th type was the sense I was getting. Is there a standard creation/update process defined for them (via API calls to KPs maybe) or will they need to be more custom? (Sorry if these are weird questions, still just getting my feet wet :-P)

**Comment by patrickkwang** [comment]
This is a good question! There is not a process, yet. Defining one is the goal of #3.

**Comment by oneilsh** [comment]
Haha, perfect, closing :)
